add display name and fix strings.

diff --git a/build/validate-install-script-sh.yml b/build/validate-install-script-sh.yml
--- a/build/validate-install-script-sh.yml
+++ b/build/validate-install-script-sh.yml
@@ -9,15 +9,17 @@ jobs:
   - bash: |
       if [grep $'\r' ./helpers/installcredprovider.sh]; then echo "CRLF line ending found" ; exit 1; fi
     workingDirectory: $(Build.SourcesDirectory)
+    displayName: Validate Install Script
 - job: LinuxInstallDefault
   steps:
   - checkout: ${{ parameters.repo }}
   - bash: | 
       ./helpers/installcredprovider.sh -Force >> ./output.log
       cat ./output.log
-      if [! grep "Microsoft.Net6.NuGet.CredentialProvider" ./output.log]; then echo "Not found"; exit 1; fi
-      if [! -d "$HOME/.nuget/plugins/netcore/CredentialProvider.Microsoft"]; then echo "Not found"; exit 1; fi
+      if [! grep "Microsoft.Net6.NuGet.CredentialProvider" ./output.log]; then echo "Expected credential provider not found"; exit 1; fi
+      if [! -d "$HOME/.nuget/plugins/netcore/CredentialProvider.Microsoft"]; then echo "Credential provider plugin directory not found"; exit 1; fi
     workingDirectory: $(Build.SourcesDirectory)
+    displayName: Validate Install Script
 - job: LinuxInstallNet8
   steps:
   - checkout: ${{ parameters.repo }}
@@ -27,7 +29,8 @@ jobs:
 
       ./helpers/installcredprovider.sh -Force >> ./output.log
       cat ./output.log
-      if [! grep "Microsoft.Net8.NuGet.CredentialProvider" ./output.log]; then echo "wrong version"; exit 1; fi
-      if [! -d "$HOME/.nuget/plugins/netcore/CredentialProvider.Microsoft"]; then echo "Not found"; exit 1; fi
+      if [! grep "Microsoft.Net8.NuGet.CredentialProvider" ./output.log]; then echo "Expected credential provider not found"; exit 1; fi
+      if [! -d "$HOME/.nuget/plugins/netcore/CredentialProvider.Microsoft"]; then echo "Credential provider plugin directory not found"; exit 1; fi
     workingDirectory: $(Build.SourcesDirectory)
+    displayName: Validate Install Script
   
