add self contained to install script validation

diff --git a/build/validate-install-script-sh.yml b/build/validate-install-script-sh.yml
--- a/build/validate-install-script-sh.yml
+++ b/build/validate-install-script-sh.yml
@@ -53,4 +53,91 @@ jobs:
       echo "Credential provider installed successfully"
     workingDirectory: $(Build.SourcesDirectory)
     displayName: Validate Install Script
-  
+- job: LinuxInstallNet8linux-x64
+  steps:
+  - checkout: ${{ parameters.repo }}
+  - bash: | 
+      export USE_NET6_ARTIFACTS_CREDENTIAL_PROVIDER=false
+      export USE_NET8_ARTIFACTS_CREDENTIAL_PROVIDER=true
+      export ARTIFACTS_CREDENTIAL_PROVIDER_RID=linux-x64
+      ./helpers/installcredprovider.sh -Force >> ./output.log
+      cat ./output.log
+
+      if ! grep "Microsoft.Net8.linux-x64.NuGet.CredentialProvider" ./output.log; then
+        echo "Expected credential provider not found"
+        exit 1
+      fi
+      if [ ! -d "$HOME/.nuget/plugins/netcore/CredentialProvider.Microsoft" ]; then
+        echo "Credential provider plugin directory not found"
+        exit 1
+      fi
+
+      echo "Credential provider installed successfully"
+    workingDirectory: $(Build.SourcesDirectory)
+    displayName: Validate Install Script
+- job: LinuxInstallNet8linux-arm64
+  steps:
+  - checkout: ${{ parameters.repo }}
+  - bash: | 
+      export USE_NET6_ARTIFACTS_CREDENTIAL_PROVIDER=false
+      export USE_NET8_ARTIFACTS_CREDENTIAL_PROVIDER=true
+      export ARTIFACTS_CREDENTIAL_PROVIDER_RID=linux-arm64
+      ./helpers/installcredprovider.sh -Force >> ./output.log
+      cat ./output.log
+
+      if ! grep "Microsoft.Net8.linux-arm64.NuGet.CredentialProvider" ./output.log; then
+        echo "Expected credential provider not found"
+        exit 1
+      fi
+      if [ ! -d "$HOME/.nuget/plugins/netcore/CredentialProvider.Microsoft" ]; then
+        echo "Credential provider plugin directory not found"
+        exit 1
+      fi
+
+      echo "Credential provider installed successfully"
+    workingDirectory: $(Build.SourcesDirectory)
+    displayName: Validate Install Script
+- job: LinuxInstallNet8osx-arm64
+  steps:
+  - checkout: ${{ parameters.repo }}
+  - bash: | 
+      export USE_NET6_ARTIFACTS_CREDENTIAL_PROVIDER=false
+      export USE_NET8_ARTIFACTS_CREDENTIAL_PROVIDER=true
+      export ARTIFACTS_CREDENTIAL_PROVIDER_RID=osx-arm64
+      ./helpers/installcredprovider.sh -Force >> ./output.log
+      cat ./output.log
+
+      if ! grep "Microsoft.Net8.osx-arm64.NuGet.CredentialProvider" ./output.log; then
+        echo "Expected credential provider not found"
+        exit 1
+      fi
+      if [ ! -d "$HOME/.nuget/plugins/netcore/CredentialProvider.Microsoft" ]; then
+        echo "Credential provider plugin directory not found"
+        exit 1
+      fi
+
+      echo "Credential provider installed successfully"
+    workingDirectory: $(Build.SourcesDirectory)
+    displayName: Validate Install Script
+- job: LinuxInstallNet8osx-x64
+  steps:
+  - checkout: ${{ parameters.repo }}
+  - bash: | 
+      export USE_NET6_ARTIFACTS_CREDENTIAL_PROVIDER=false
+      export USE_NET8_ARTIFACTS_CREDENTIAL_PROVIDER=true
+      export ARTIFACTS_CREDENTIAL_PROVIDER_RID=osx-x64
+      ./helpers/installcredprovider.sh -Force >> ./output.log
+      cat ./output.log
+
+      if ! grep "Microsoft.Net8.osx-x64.NuGet.CredentialProvider" ./output.log; then
+        echo "Expected credential provider not found"
+        exit 1
+      fi
+      if [ ! -d "$HOME/.nuget/plugins/netcore/CredentialProvider.Microsoft" ]; then
+        echo "Credential provider plugin directory not found"
+        exit 1
+      fi
+
+      echo "Credential provider installed successfully"
+    workingDirectory: $(Build.SourcesDirectory)
+    displayName: Validate Install Script
